### ISSUE TITLE
Please Fix

### ISSUE THREAD

**Issue by spindizzytech** [jazzay/flecs-rs#10]
Can you please fix this and upgrade to the latest version of flecs?

error[E0425]: cannot find value `FLECS__EEcsRest` in this scope
    --> src\world.rs:307:33
     |
307  |     let rest_comp_id = unsafe { FLECS__EEcsRest as u64 };
     |                                 ^^^^^^^^^^^^^^^ help: a static with a similar name exists: `FLECS__EEcsBel`
     |
    ::: c:\Users\MBS\base\flecs-rs\target\wasm32-unknown-emscripten\debug\build\flecs-5fc36f07bf0dcba7\out/bindings.rs:5123:5
     |
5123 |     pub static mut FLECS__EEcsBel: ecs_entity_t;
     |     -------------------------------------------- similarly named static `FLECS__EEcsBel` defined here

error[E0412]: cannot find type `EcsRest` in this scope
   --> src\world.rs:308:44
    |
308 |         let rest_comp_size = std::mem::size_of::<EcsRest>();
    |                                                  ^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
305 | impl<EcsRest> World {
    |     +++++++++

error[E0412]: cannot find type `EcsRest` in this scope
   --> src\world.rs:310:18
    |
310 |         let rest_data: EcsRest = unsafe { MaybeUninit::zeroed().assume_init() };
    |                        ^^^^^^^ not found in this scope

error[E0412]: cannot find type `EcsRest` in this scope
   --> src\world.rs:317:26
    |
317 |                 &rest_data as *const EcsRest as *const ::std::os::raw::c_void)
    |

**Comment by jazzay** [comment]
@spindizzytech coincidentally I just started working on the upgrades today. Since it has not been updated since original 3.0, I need to work my way through each release. I've updated to 3.1.2 as of now. Goal to be at latest 3.2 soon.

**Comment by spindizzytech** [comment]
Much appreciated!

**Comment by jazzay** [comment]
@spindizzytech  I've upgraded to the latest Flecs 3.2.1, and published a new version on crates.io.

Note if you are still having issues with the Wasm target, please submit a PR to fix, as I don't actively maintain that right now. Looks like from the errors above we just need to exclude the Rest server API perhaps when building for Wasm.
