### ISSUE TITLE
crates.io uses read-only file system

### ISSUE THREAD

**Issue by toyboot4e** [jazzay/flecs-rs#2]
So the `.expect` would always fail:

https://github.com/jazzay/flecs-rs/blob/012129c7645b5391fbaf1e943151f088e2e8d4fe/build.rs#L41

`.ok();` would be better.

---

[My past failure for reference](https://docs.rs/crate/fna3d/0.1.3/builds/322773):

```
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 30, kind: Other, message: "Read-only file system" }', 
```

**Comment by jazzay** [comment]
This is no longer an issue as build.rs was changed back to using OUT_DIR.
