### ISSUE TITLE
No way to query based on raw component id's

### ISSUE THREAD

**Issue by MalekiRe** [jazzay/flecs-rs#4]
If I have code like such
`let mut world = flecs::world::World::new();
    let component_id: EntityId = world.component_dynamic("transform", Layout::for_value(&Transform::default()));

    let mut entity = world.entity();
    let mut e2 = entity.add_dynamic("transform");

    let mut edited_transform = Transform::default();
    edited_transform.pos.x = 10.0;

    let reference: &mut Transform = &mut edited_transform;

    e2.set_dynamic("transform", bytemuck::bytes_of_mut(reference));
    `
 I am unable to actually query the world for entities using the `component_id`.
 Looking at the source code, In the impl for filter, you use raw ids
 `
 pub fn new_1<A: Component>(world: *mut ecs_world_t) -> Self {
		let mut desc: ecs_filter_desc_t = unsafe { MaybeUninit::zeroed().assume_init() };

		// TODO: add batch type lookup!
		desc.terms[0].id = WorldInfoCache::get_component_id_for_type::<A>(world).expect("Component type not registered!");

		let filter = unsafe { ecs_filter_init(world, &desc) };
		Filter { world, filter }
	}
`
So this would be greatly appreciated.

**Comment by jazzay** [comment]
I've added a basic FilterBuilder api that allows you do this:
```rs
let mut world = World::new();
let data_comp = world.component_dynamic(DATA_IDENTIFIER, Layout::new::<DataValue>());

let filter = world.filter_builder()
    .term::<Position>()
    .term_dynamic(data_comp)
    .build();

filter.iter(|it| {
    let positions = it.field::<Position>(1);
    let datas = it.field_dynamic(2);

    for index in 0..it.count() {
	let pos = positions.get(index);
	let data = datas.get(index);
	println!("   {:?}, {:?}", pos, data);
    }
});
```

**Comment by jazzay** [comment]
Fixed in:
https://github.com/jazzay/flecs-rs/commit/120d2eb21745a5d53368f6d4f8248c20742dc3eb
